# Use postgres/example user/password credentials
version: '3.1'

services:

  postgres:
    image: postgres:14.4-alpine
    restart: always
    environment:
      POSTGRES_DB: hr_managing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    # env_file:
    #   - ./server/.env

  nest:
    build:
      context: server
      dockerfile: dev.Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./server/src:/src
      - ./server/dist:/dist
    depends_on:
      - postgres
